spring.application.name=dailylog

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5430/dailylog}
spring.datasource.username=${DATABASE_USERNAME:dailylog}
spring.datasource.password=${DATABASE_PASSWORD:dailylog}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.security.user.name = ${APP_USERNAME}
spring.security.user.password = ${APP_PASSWORD}