spring.application.name=dailylog

spring.datasource.url=jdbc:postgresql://localhost:5430/dailylog
spring.datasource.username=dailylog
spring.datasource.password=dailylog
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.security.user.name = ${APP_USERNAME}
spring.security.user.password = ${APP_PASSWORD}